### ISSUE TITLE
install.sh Permission Denied

### ISSUE THREAD

**Issue by burkybang** [Alticha/RootlessInstaller#6]
![image](https://user-images.githubusercontent.com/927886/53132121-dbdafc00-35c2-11e9-9300-f7b4a1bad410.png)

iPhone 8 Plus
iOS 12.1.1 Beta 3
rootlessJB 3.2.7
RootlessInstaller 1.0.2

**Comment by ghost** [comment]
i got the same thing. I installed the 1.0.1 and works fine. However i cannot install 1.0.2 anymore impactor says its already installed..... I deleted it

**Comment by Alticha** [comment]
you must prefix with "sh"
sh "$(find /var/containers/Bundle/Application | grep RootlessInstaller.app/install.sh)"

**Comment by ghost** [comment]
> you must prefix with "sh"
> sh "$(find /var/containers/Bundle/Application | grep RootlessInstaller.app/install.sh)"

Ill have to try this again. But i have another issue if you could help that would be great. I had version 1.0.2 installed and didnt want to open so i removed it and tried to install via IPA however impactor said it was installed and could not install again. Each time i re-spring it reinstalled version 1.0.2 and gave same error. How do i completely remove it? Why is it reinstalling after resping?
